version: '3.8'

services:
  service:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true

    environment:
      - swagger.server.url=https://service.spacecraftEvents.imertetsu.me/api
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true